name: CI Build and Test (Manual)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Build Core Package
        run: cd core && npm install && npm run build

      - name: Install & Build Visualization Package
        run: cd visualization && npm install && npm run build
