name: CI Diagnostic

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 1. Display Recursive File Structure
        run: ls -R

      - name: 2. Display Root package.json
        run: cat package.json

      - name: 3. Display Core package.json
        run: |
          echo "--- Contents of packages/core/package.json ---"
          cat packages/core/package.json

      - name: 4. Display Visualization package.json
        run: |
          echo "--- Contents of packages/visualization/package.json ---"
          cat packages/visualization/package.json
